-- USE Full University Record Management System
-- PostgreSQL conversion of 01_create_use_full_database_v6_clean_roles.sql
-- This script creates a PostgreSQL schema named use_record_management inside the current database.

DROP SCHEMA IF EXISTS use_record_management CASCADE;
CREATE SCHEMA use_record_management;
SET search_path TO use_record_management, public;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- 1. Organisation and academic structure
-- =========================================================

CREATE TABLE college (
    college_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_code VARCHAR(10) NOT NULL UNIQUE,
    college_name VARCHAR(120) NOT NULL UNIQUE,
    has_direct_students BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE department (
    department_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    college_id INT NOT NULL,
    department_code VARCHAR(10) NOT NULL UNIQUE,
    department_name VARCHAR(150) NOT NULL,
    research_area_summary VARCHAR(255) NULL,
    is_teaching_department BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_department_college FOREIGN KEY (college_id)
        REFERENCES college(college_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE administrative_unit (
    admin_unit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code VARCHAR(10) NOT NULL UNIQUE,
    unit_name VARCHAR(120) NOT NULL UNIQUE,
    unit_description VARCHAR(255) NULL
);

-- =========================================================
-- 2. Programme and curriculum tables
-- =========================================================

CREATE TABLE programme (
    programme_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_code VARCHAR(20) NOT NULL UNIQUE,
    programme_name VARCHAR(180) NOT NULL,
    degree_awarded VARCHAR(40) CHECK (degree_awarded IN ('B.Sc.', 'M.Sc.', 'Ph.D.')) NOT NULL,
    college_id INT NOT NULL,
    department_id INT NOT NULL,
    duration_years_min SMALLINT NOT NULL,
    duration_years_max SMALLINT NOT NULL,
    required_credit_hours SMALLINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_programme_duration CHECK (duration_years_min <= duration_years_max),
    CONSTRAINT chk_programme_credits CHECK (required_credit_hours > 0),
    CONSTRAINT fk_programme_college FOREIGN KEY (college_id)
        REFERENCES college(college_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_programme_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================================================
-- 3. People and role tables
-- =========================================================

CREATE TABLE person (
    person_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(40) NULL,
    nationality VARCHAR(80) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE person_contact (
    contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    contact_type VARCHAR(40) CHECK (contact_type IN ('Email', 'Mobile', 'Address', 'Emergency', 'Other')) NOT NULL,
    contact_value VARCHAR(255) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_person_contact_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE student (
    student_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL UNIQUE,
    student_number VARCHAR(30) NOT NULL UNIQUE,
    programme_id INT NOT NULL,
    date_of_birth DATE NOT NULL,
    enrolment_year SMALLINT NOT NULL,
    year_of_study SMALLINT NOT NULL,
    admission_type VARCHAR(40) CHECK (admission_type IN ('Local', 'International', 'Exchange')) NOT NULL DEFAULT 'International',
    student_status VARCHAR(40) CHECK (student_status IN ('Active', 'Suspended', 'Withdrawn', 'Graduated')) NOT NULL DEFAULT 'Active',
    graduation_status VARCHAR(40) CHECK (graduation_status IN ('Not eligible', 'Eligible', 'Graduated')) NOT NULL DEFAULT 'Not eligible',
    CONSTRAINT chk_student_year_of_study CHECK (year_of_study BETWEEN 1 AND 8),
    CONSTRAINT fk_student_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_student_programme FOREIGN KEY (programme_id)
        REFERENCES programme(programme_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE lecturer (
    lecturer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL UNIQUE,
    lecturer_number VARCHAR(35) NOT NULL UNIQUE,
    department_id INT NOT NULL,
    academic_rank VARCHAR(40) CHECK (academic_rank IN ('Lecturer', 'Assistant Professor', 'Associate Professor', 'Professor')) NOT NULL,
    employment_type VARCHAR(40) CHECK (employment_type IN ('Full-time', 'Part-time', 'Visiting', 'Contract')) NOT NULL DEFAULT 'Full-time',
    office_location VARCHAR(80) NULL,
    joining_year SMALLINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_lecturer_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_lecturer_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE administrator (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL UNIQUE,
    admin_number VARCHAR(30) NOT NULL UNIQUE,
    admin_unit_id INT NOT NULL,
    college_id INT NULL,
    department_id INT NULL,
    job_title VARCHAR(120) NOT NULL,
    employment_type VARCHAR(40) CHECK (employment_type IN ('Full-time', 'Part-time', 'Contract')) NOT NULL DEFAULT 'Full-time',
    joining_year SMALLINT NOT NULL,
    CONSTRAINT fk_administrator_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_administrator_unit FOREIGN KEY (admin_unit_id)
        REFERENCES administrative_unit(admin_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_administrator_college FOREIGN KEY (college_id)
        REFERENCES college(college_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_administrator_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE non_academic_staff (
    staff_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL UNIQUE,
    staff_number VARCHAR(30) NOT NULL UNIQUE,
    admin_unit_id INT NULL,
    department_id INT NULL,
    job_title VARCHAR(120) NOT NULL,
    employment_type VARCHAR(40) CHECK (employment_type IN ('Full-time', 'Part-time', 'Contract')) NOT NULL DEFAULT 'Full-time',
    contract_start_date DATE NOT NULL,
    contract_end_date DATE NULL,
    salary_amount DECIMAL(10,2) NOT NULL,
    salary_currency CHAR(3) NOT NULL DEFAULT 'USD',
    CONSTRAINT chk_staff_contract_dates CHECK (contract_end_date IS NULL OR contract_start_date < contract_end_date),
    CONSTRAINT fk_staff_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_staff_unit FOREIGN KEY (admin_unit_id)
        REFERENCES administrative_unit(admin_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_staff_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE staff_emergency_contact (
    emergency_contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL,
    contact_name VARCHAR(120) NOT NULL,
    relationship VARCHAR(60) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(150) NULL,
    CONSTRAINT fk_staff_emergency_person FOREIGN KEY (person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- =========================================================
-- 4. Lecturer attributes and advising
-- =========================================================

CREATE TABLE lecturer_qualification (
    qualification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT NOT NULL,
    qualification_name VARCHAR(150) NOT NULL,
    field_of_study VARCHAR(120) NOT NULL,
    awarding_institution VARCHAR(180) NOT NULL,
    award_year SMALLINT NOT NULL,
    CONSTRAINT fk_qualification_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE lecturer_expertise (
    expertise_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT NOT NULL,
    expertise_area VARCHAR(150) NOT NULL,
    CONSTRAINT uq_lecturer_expertise UNIQUE (lecturer_id, expertise_area),
    CONSTRAINT fk_expertise_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE lecturer_research_interest (
    interest_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id INT NOT NULL,
    research_interest VARCHAR(180) NOT NULL,
    CONSTRAINT uq_lecturer_interest UNIQUE (lecturer_id, research_interest),
    CONSTRAINT fk_interest_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE advisor_assignment (
    advisor_assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    lecturer_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_advisor_dates CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT fk_advisor_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_advisor_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================================================
-- 5. Course, term and enrolment
-- =========================================================

CREATE TABLE academic_term (
    term_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year VARCHAR(9) NOT NULL,
    term_name VARCHAR(40) CHECK (term_name IN ('Fall', 'Spring', 'Summer')) NOT NULL,
    term_sequence SMALLINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_weeks SMALLINT NOT NULL,
    is_regular_term BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_academic_year_term UNIQUE (academic_year, term_name),
    CONSTRAINT chk_term_dates CHECK (start_date < end_date),
    CONSTRAINT chk_term_sequence CHECK (term_sequence IN (1, 2, 3)),
    CONSTRAINT chk_term_duration CHECK (duration_weeks IN (8, 16))
);

CREATE TABLE course (
    course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(20) NOT NULL UNIQUE,
    course_name VARCHAR(180) NOT NULL,
    description TEXT NULL,
    department_id INT NOT NULL,
    course_level SMALLINT NOT NULL,
    credit_hours SMALLINT NOT NULL,
    course_type VARCHAR(40) CHECK (course_type IN ('Lecture', 'Lab', 'Thesis', 'Dissertation', 'Capstone', 'Seminar')) NOT NULL DEFAULT 'Lecture',
    parent_course_id INT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_course_level CHECK (course_level IN (100, 200, 300, 400, 500, 600, 700, 800, 900)),
    CONSTRAINT chk_course_credit_hours CHECK (credit_hours BETWEEN 1 AND 14),
    CONSTRAINT fk_course_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_course_parent FOREIGN KEY (parent_course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE course_material (
    material_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL,
    material_title VARCHAR(180) NOT NULL,
    material_type VARCHAR(40) CHECK (material_type IN ('Textbook', 'Lab manual', 'Reading', 'Software', 'Website', 'Other')) NOT NULL,
    material_reference VARCHAR(255) NOT NULL,
    CONSTRAINT fk_course_material_course FOREIGN KEY (course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE course_prerequisite (
    course_id INT NOT NULL,
    prerequisite_course_id INT NOT NULL,
    prerequisite_type VARCHAR(40) CHECK (prerequisite_type IN ('Prerequisite', 'Corequisite', 'Recommended')) NOT NULL DEFAULT 'Prerequisite',
    minimum_grade VARCHAR(10) NOT NULL DEFAULT 'Pass',
    can_be_concurrent BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT fk_course_prereq_course FOREIGN KEY (course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_course_prereq_required FOREIGN KEY (prerequisite_course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE programme_course_requirement (
    requirement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id INT NOT NULL,
    course_id INT NOT NULL,
    requirement_type VARCHAR(40) CHECK (requirement_type IN ('Foundation', 'Core', 'Lab', 'Research', 'Thesis', 'Dissertation', 'Capstone')) NOT NULL,
    recommended_year SMALLINT NOT NULL,
    recommended_term VARCHAR(40) CHECK (recommended_term IN ('Fall', 'Spring', 'Summer')) NULL,
    is_required_for_graduation BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_programme_required_course UNIQUE (programme_id, course_id),
    CONSTRAINT chk_requirement_year CHECK (recommended_year BETWEEN 1 AND 8),
    CONSTRAINT fk_requirement_programme FOREIGN KEY (programme_id)
        REFERENCES programme(programme_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_requirement_course FOREIGN KEY (course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE elective_group (
    elective_group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_id INT NOT NULL,
    group_name VARCHAR(150) NOT NULL,
    minimum_credit_hours SMALLINT NOT NULL,
    recommended_year SMALLINT NULL,
    notes VARCHAR(255) NULL,
    CONSTRAINT uq_programme_elective_group UNIQUE (programme_id, group_name),
    CONSTRAINT chk_elective_min_credits CHECK (minimum_credit_hours > 0),
    CONSTRAINT fk_elective_group_programme FOREIGN KEY (programme_id)
        REFERENCES programme(programme_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE elective_group_course (
    elective_group_id INT NOT NULL,
    course_id INT NOT NULL,
    PRIMARY KEY (elective_group_id, course_id),
    CONSTRAINT fk_elective_course_group FOREIGN KEY (elective_group_id)
        REFERENCES elective_group(elective_group_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_elective_course_course FOREIGN KEY (course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE course_offering (
    offering_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INT NOT NULL,
    term_id INT NOT NULL,
    admin_id INT NOT NULL,
    section_code VARCHAR(10) NOT NULL DEFAULT 'A',
    capacity SMALLINT NOT NULL DEFAULT 35,
    delivery_mode VARCHAR(40) CHECK (delivery_mode IN ('In person', 'Online', 'Hybrid', 'Lab')) NOT NULL DEFAULT 'In person',
    schedule_days VARCHAR(30) NULL,
    start_time TIME NULL,
    end_time TIME NULL,
    status VARCHAR(40) CHECK (status IN ('Offered', 'Closed', 'Cancelled')) NOT NULL DEFAULT 'Offered',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_course_term_section UNIQUE (course_id, term_id, section_code),
    CONSTRAINT chk_offering_capacity CHECK (capacity > 0),
    CONSTRAINT chk_offering_time CHECK (start_time IS NULL OR end_time IS NULL OR start_time < end_time),
    CONSTRAINT fk_offering_course FOREIGN KEY (course_id)
        REFERENCES course(course_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_offering_term FOREIGN KEY (term_id)
        REFERENCES academic_term(term_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_offering_admin FOREIGN KEY (admin_id)
        REFERENCES administrator(admin_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE offering_lecturer (
    offering_id INT NOT NULL,
    lecturer_id INT NOT NULL,
    teaching_role VARCHAR(40) CHECK (teaching_role IN ('Primary', 'Co-teacher', 'Lab instructor', 'Supervisor')) NOT NULL DEFAULT 'Primary',
    workload_credit_hours DECIMAL(4,1) NOT NULL DEFAULT 3.0,
    PRIMARY KEY (offering_id, lecturer_id),
    CONSTRAINT chk_workload_credit_hours CHECK (workload_credit_hours > 0),
    CONSTRAINT fk_offering_lecturer_offering FOREIGN KEY (offering_id)
        REFERENCES course_offering(offering_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_offering_lecturer_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE enrolment (
    enrolment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    offering_id INT NOT NULL,
    enrolment_date DATE NOT NULL,
    enrolment_status VARCHAR(40) CHECK (enrolment_status IN ('Enrolled', 'Withdrawn', 'Completed')) NOT NULL DEFAULT 'Enrolled',
    result_status VARCHAR(40) CHECK (result_status IN ('In progress', 'Passed', 'Failed')) NOT NULL DEFAULT 'In progress',
    result_recorded_at TIMESTAMP NULL,
    CONSTRAINT uq_student_offering UNIQUE (student_id, offering_id),
    CONSTRAINT fk_enrolment_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_enrolment_offering FOREIGN KEY (offering_id)
        REFERENCES course_offering(offering_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE grade (
    grade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrolment_id INT NOT NULL,
    assessment_type VARCHAR(40) CHECK (assessment_type IN ('Midterm', 'Final', 'Coursework', 'Lab', 'Project', 'Overall')) NOT NULL,
    numeric_grade DECIMAL(5,2) NOT NULL,
    letter_grade VARCHAR(3) NULL,
    recorded_by_lecturer_id INT NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_numeric_grade CHECK (numeric_grade BETWEEN 0 AND 100),
    CONSTRAINT uq_enrolment_assessment UNIQUE (enrolment_id, assessment_type),
    CONSTRAINT fk_grade_enrolment FOREIGN KEY (enrolment_id)
        REFERENCES enrolment(enrolment_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_grade_lecturer FOREIGN KEY (recorded_by_lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================================================
-- 6. Student life and disciplinary tables
-- =========================================================

CREATE TABLE disciplinary_record (
    disciplinary_record_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    incident_date DATE NOT NULL,
    incident_type VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    outcome VARCHAR(255) NULL,
    record_status VARCHAR(40) CHECK (record_status IN ('Open', 'Closed', 'Appealed')) NOT NULL DEFAULT 'Open',
    CONSTRAINT fk_disciplinary_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE student_organisation (
    organisation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_code VARCHAR(30) NOT NULL UNIQUE,
    organisation_name VARCHAR(150) NOT NULL UNIQUE,
    organisation_type VARCHAR(40) CHECK (organisation_type IN ('Academic', 'Cultural', 'Sport', 'Service', 'Professional')) NOT NULL,
    advisor_lecturer_id INT NULL,
    CONSTRAINT fk_organisation_advisor FOREIGN KEY (advisor_lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE student_organisation_registration (
    registration_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    organisation_id INT NOT NULL,
    registration_date DATE NOT NULL,
    role_in_organisation VARCHAR(80) NOT NULL DEFAULT 'Member',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_student_organisation UNIQUE (student_id, organisation_id),
    CONSTRAINT fk_org_registration_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_org_registration_organisation FOREIGN KEY (organisation_id)
        REFERENCES student_organisation(organisation_id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- =========================================================
-- 7. Research, publication and committee tables
-- =========================================================

CREATE TABLE research_centre (
    research_centre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    centre_code VARCHAR(30) NOT NULL UNIQUE,
    centre_name VARCHAR(180) NOT NULL UNIQUE,
    host_college_id INT NOT NULL,
    description TEXT NULL,
    CONSTRAINT fk_centre_host_college FOREIGN KEY (host_college_id)
        REFERENCES college(college_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE research_group (
    research_group_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(35) NOT NULL UNIQUE,
    research_centre_id INT NOT NULL,
    department_id INT NOT NULL,
    group_name VARCHAR(180) NOT NULL,
    head_lecturer_id INT NOT NULL UNIQUE,
    start_date DATE NOT NULL,
    CONSTRAINT fk_group_centre FOREIGN KEY (research_centre_id)
        REFERENCES research_centre(research_centre_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_group_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_group_head FOREIGN KEY (head_lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE research_group_member (
    group_member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    research_group_id INT NOT NULL,
    lecturer_id INT NOT NULL,
    member_role VARCHAR(40) CHECK (member_role IN ('Head', 'Member', 'Associate Member')) NOT NULL DEFAULT 'Member',
    start_date DATE NOT NULL,
    end_date DATE NULL,
    CONSTRAINT uq_group_lecturer UNIQUE (research_group_id, lecturer_id),
    CONSTRAINT chk_group_member_dates CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT fk_group_member_group FOREIGN KEY (research_group_id)
        REFERENCES research_group(research_group_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_group_member_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE research_project (
    project_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(30) NOT NULL UNIQUE,
    project_title VARCHAR(220) NOT NULL,
    research_group_id INT NOT NULL,
    principal_investigator_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    project_status VARCHAR(40) CHECK (project_status IN ('Planned', 'Active', 'Completed', 'Suspended')) NOT NULL DEFAULT 'Active',
    summary TEXT NULL,
    CONSTRAINT chk_project_dates CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT fk_project_group FOREIGN KEY (research_group_id)
        REFERENCES research_group(research_group_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_project_pi FOREIGN KEY (principal_investigator_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE research_project_member (
    project_member_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT NOT NULL,
    member_type VARCHAR(40) CHECK (member_type IN ('Lecturer', 'Student', 'Staff')) NOT NULL,
    lecturer_id INT NULL,
    student_id INT NULL,
    staff_id INT NULL,
    role_in_project VARCHAR(80) NOT NULL,
    CONSTRAINT fk_project_member_project FOREIGN KEY (project_id)
        REFERENCES research_project(project_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_member_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_member_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_member_staff FOREIGN KEY (staff_id)
        REFERENCES non_academic_staff(staff_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE funding_source (
    funding_source_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_code VARCHAR(30) NOT NULL UNIQUE,
    source_name VARCHAR(180) NOT NULL,
    source_type VARCHAR(40) CHECK (source_type IN ('Government', 'Industry', 'University', 'International', 'Other')) NOT NULL
);

CREATE TABLE project_funding (
    project_funding_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT NOT NULL,
    funding_source_id INT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'USD',
    funding_year SMALLINT NOT NULL,
    CONSTRAINT chk_project_funding_amount CHECK (amount >= 0),
    CONSTRAINT fk_project_funding_project FOREIGN KEY (project_id)
        REFERENCES research_project(project_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_funding_source FOREIGN KEY (funding_source_id)
        REFERENCES funding_source(funding_source_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE publication (
    publication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_code VARCHAR(30) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    publication_type VARCHAR(40) CHECK (publication_type IN ('Journal', 'Conference', 'Book Chapter', 'Report', 'Patent')) NOT NULL,
    publication_year SMALLINT NOT NULL,
    doi_or_url VARCHAR(255) NULL
);

CREATE TABLE lecturer_publication (
    lecturer_id INT NOT NULL,
    publication_id INT NOT NULL,
    author_order SMALLINT NOT NULL,
    PRIMARY KEY (lecturer_id, publication_id),
    CONSTRAINT chk_author_order CHECK (author_order > 0),
    CONSTRAINT fk_lecturer_publication_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_lecturer_publication_publication FOREIGN KEY (publication_id)
        REFERENCES publication(publication_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE project_publication (
    project_id INT NOT NULL,
    publication_id INT NOT NULL,
    PRIMARY KEY (project_id, publication_id),
    CONSTRAINT fk_project_publication_project FOREIGN KEY (project_id)
        REFERENCES research_project(project_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_publication_publication FOREIGN KEY (publication_id)
        REFERENCES publication(publication_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE project_outcome (
    outcome_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INT NOT NULL,
    outcome_type VARCHAR(40) CHECK (outcome_type IN ('Dataset', 'Prototype', 'Report', 'Patent', 'Publication', 'Policy Brief', 'Other')) NOT NULL,
    outcome_description TEXT NOT NULL,
    outcome_date DATE NOT NULL,
    CONSTRAINT fk_project_outcome_project FOREIGN KEY (project_id)
        REFERENCES research_project(project_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE committee (
    committee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    committee_code VARCHAR(30) NOT NULL UNIQUE,
    committee_name VARCHAR(180) NOT NULL,
    department_id INT NULL,
    admin_unit_id INT NULL,
    committee_type VARCHAR(40) CHECK (committee_type IN ('College', 'Department', 'University', 'Research')) NOT NULL,
    CONSTRAINT fk_committee_department FOREIGN KEY (department_id)
        REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_committee_unit FOREIGN KEY (admin_unit_id)
        REFERENCES administrative_unit(admin_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE committee_membership (
    membership_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    committee_id INT NOT NULL,
    lecturer_id INT NOT NULL,
    committee_role VARCHAR(80) NOT NULL DEFAULT 'Member',
    start_date DATE NOT NULL,
    end_date DATE NULL,
    CONSTRAINT uq_committee_lecturer UNIQUE (committee_id, lecturer_id),
    CONSTRAINT chk_committee_dates CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT fk_committee_membership_committee FOREIGN KEY (committee_id)
        REFERENCES committee(committee_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_committee_membership_lecturer FOREIGN KEY (lecturer_id)
        REFERENCES lecturer(lecturer_id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- =========================================================
-- 8. Student employment and supervision
-- =========================================================

CREATE TABLE student_employment (
    student_employment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_employee_number VARCHAR(30) NOT NULL UNIQUE,
    student_id INT NOT NULL,
    programme_id INT NOT NULL,
    admin_unit_id INT NOT NULL,
    job_title VARCHAR(120) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    hourly_rate DECIMAL(8,2) NULL,
    CONSTRAINT chk_student_employment_dates CHECK (end_date IS NULL OR start_date < end_date),
    CONSTRAINT fk_student_employment_student FOREIGN KEY (student_id)
        REFERENCES student(student_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_student_employment_programme FOREIGN KEY (programme_id)
        REFERENCES programme(programme_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_student_employment_unit FOREIGN KEY (admin_unit_id)
        REFERENCES administrative_unit(admin_unit_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE employee_supervision (
    supervision_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_employment_id INT NOT NULL,
    supervisor_person_id INT NOT NULL,
    supervision_start_date DATE NOT NULL,
    supervision_end_date DATE NULL,
    CONSTRAINT chk_supervision_dates CHECK (supervision_end_date IS NULL OR supervision_start_date < supervision_end_date),
    CONSTRAINT fk_supervision_student_employment FOREIGN KEY (student_employment_id)
        REFERENCES student_employment(student_employment_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_supervision_person FOREIGN KEY (supervisor_person_id)
        REFERENCES person(person_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- =========================================================
-- 9. Security and audit support
-- =========================================================

CREATE TABLE dba_audit_log (
    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_name VARCHAR(100) NOT NULL,
    action_detail VARCHAR(255) NOT NULL,
    action_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE security_demo_encrypted_note (
    note_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_title VARCHAR(80) NOT NULL,
    encrypted_note BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =========================================================
-- 10. Indexes
-- =========================================================

CREATE INDEX idx_person_name ON person(last_name, first_name);
CREATE INDEX idx_student_number ON student(student_number);
CREATE INDEX idx_student_programme ON student(programme_id);
CREATE INDEX idx_lecturer_number ON lecturer(lecturer_number);
CREATE INDEX idx_lecturer_department ON lecturer(department_id);
CREATE INDEX idx_admin_number ON administrator(admin_number);
CREATE INDEX idx_staff_number ON non_academic_staff(staff_number);
CREATE INDEX idx_course_department_level ON course(department_id, course_level);
CREATE INDEX idx_course_offering_term ON course_offering(term_id);
CREATE INDEX idx_course_offering_course ON course_offering(course_id);
CREATE INDEX idx_enrolment_student ON enrolment(student_id);
CREATE INDEX idx_enrolment_offering ON enrolment(offering_id);
CREATE INDEX idx_grade_enrolment ON grade(enrolment_id);
CREATE INDEX idx_prereq_required_course ON course_prerequisite(prerequisite_course_id);
CREATE INDEX idx_project_pi ON research_project(principal_investigator_id);
CREATE INDEX idx_publication_year ON publication(publication_year);



-- =========================================================
-- 11. Triggers - PostgreSQL PL/pgSQL equivalents
-- =========================================================

CREATE OR REPLACE FUNCTION fn_course_prereq_no_self()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.course_id = NEW.prerequisite_course_id THEN
        RAISE EXCEPTION 'A course cannot be a prerequisite of itself.';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_course_prereq_no_self_before_insert
BEFORE INSERT ON course_prerequisite
FOR EACH ROW EXECUTE FUNCTION fn_course_prereq_no_self();

CREATE TRIGGER trg_course_prereq_no_self_before_update
BEFORE UPDATE ON course_prerequisite
FOR EACH ROW EXECUTE FUNCTION fn_course_prereq_no_self();

CREATE OR REPLACE FUNCTION fn_enrolment_prereq_check()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    missing_prereqs INTEGER := 0;
BEGIN
    IF TG_OP = 'INSERT' OR NEW.student_id <> OLD.student_id OR NEW.offering_id <> OLD.offering_id THEN
        SELECT COUNT(*) INTO missing_prereqs
        FROM course_prerequisite cp
        JOIN course_offering target_offering ON target_offering.course_id = cp.course_id
        JOIN academic_term target_term ON target_term.term_id = target_offering.term_id
        WHERE target_offering.offering_id = NEW.offering_id
          AND NOT EXISTS (
              SELECT 1
              FROM enrolment previous_enrolment
              JOIN course_offering previous_offering
                  ON previous_offering.offering_id = previous_enrolment.offering_id
              JOIN academic_term previous_term
                  ON previous_term.term_id = previous_offering.term_id
              WHERE previous_enrolment.student_id = NEW.student_id
                AND previous_offering.course_id = cp.prerequisite_course_id
                AND previous_enrolment.result_status = 'Passed'
                AND (
                    (cp.prerequisite_type = 'Prerequisite'
                        AND cp.can_be_concurrent = FALSE
                        AND previous_term.start_date < target_term.start_date)
                    OR
                    ((cp.prerequisite_type <> 'Prerequisite'
                        OR cp.can_be_concurrent = TRUE)
                        AND previous_term.start_date <= target_term.start_date)
                )
          );

        IF missing_prereqs > 0 THEN
            IF TG_OP = 'INSERT' THEN
                RAISE EXCEPTION 'Enrolment rejected: prerequisite or corequisite requirement is not satisfied.';
            ELSE
                RAISE EXCEPTION 'Update rejected: prerequisite or corequisite requirement is not satisfied.';
            END IF;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_enrolment_prereq_before_insert
BEFORE INSERT ON enrolment
FOR EACH ROW EXECUTE FUNCTION fn_enrolment_prereq_check();

CREATE TRIGGER trg_enrolment_prereq_before_update
BEFORE UPDATE ON enrolment
FOR EACH ROW EXECUTE FUNCTION fn_enrolment_prereq_check();

CREATE OR REPLACE FUNCTION fn_one_current_advisor()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_current = TRUE AND EXISTS (
        SELECT 1
        FROM advisor_assignment aa
        WHERE aa.student_id = NEW.student_id
          AND aa.is_current = TRUE
          AND (TG_OP = 'INSERT' OR aa.advisor_assignment_id <> OLD.advisor_assignment_id)
    ) THEN
        IF TG_OP = 'INSERT' THEN
            RAISE EXCEPTION 'Advisor assignment rejected: student already has a current advisor.';
        ELSE
            RAISE EXCEPTION 'Advisor update rejected: student already has another current advisor.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_one_current_advisor_before_insert
BEFORE INSERT ON advisor_assignment
FOR EACH ROW EXECUTE FUNCTION fn_one_current_advisor();

CREATE TRIGGER trg_one_current_advisor_before_update
BEFORE UPDATE ON advisor_assignment
FOR EACH ROW EXECUTE FUNCTION fn_one_current_advisor();

CREATE OR REPLACE FUNCTION fn_staff_assignment_required()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.admin_unit_id IS NULL AND NEW.department_id IS NULL THEN
        IF TG_OP = 'INSERT' THEN
            RAISE EXCEPTION 'Staff assignment rejected: admin_unit_id or department_id is required.';
        ELSE
            RAISE EXCEPTION 'Staff update rejected: admin_unit_id or department_id is required.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_staff_assignment_before_insert
BEFORE INSERT ON non_academic_staff
FOR EACH ROW EXECUTE FUNCTION fn_staff_assignment_required();

CREATE TRIGGER trg_staff_assignment_before_update
BEFORE UPDATE ON non_academic_staff
FOR EACH ROW EXECUTE FUNCTION fn_staff_assignment_required();

CREATE OR REPLACE FUNCTION fn_project_member_one_type()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    ref_count INTEGER;
BEGIN
    ref_count := (CASE WHEN NEW.lecturer_id IS NOT NULL THEN 1 ELSE 0 END)
               + (CASE WHEN NEW.student_id IS NOT NULL THEN 1 ELSE 0 END)
               + (CASE WHEN NEW.staff_id IS NOT NULL THEN 1 ELSE 0 END);
    IF ref_count <> 1 THEN
        IF TG_OP = 'INSERT' THEN
            RAISE EXCEPTION 'Project member rejected: exactly one member reference is required.';
        ELSE
            RAISE EXCEPTION 'Project member update rejected: exactly one member reference is required.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_project_member_one_type_before_insert
BEFORE INSERT ON research_project_member
FOR EACH ROW EXECUTE FUNCTION fn_project_member_one_type();

CREATE TRIGGER trg_project_member_one_type_before_update
BEFORE UPDATE ON research_project_member
FOR EACH ROW EXECUTE FUNCTION fn_project_member_one_type();

CREATE OR REPLACE FUNCTION fn_committee_owner_required()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.department_id IS NULL AND NEW.admin_unit_id IS NULL THEN
        IF TG_OP = 'INSERT' THEN
            RAISE EXCEPTION 'Committee rejected: department_id or admin_unit_id is required.';
        ELSE
            RAISE EXCEPTION 'Committee update rejected: department_id or admin_unit_id is required.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_committee_owner_before_insert
BEFORE INSERT ON committee
FOR EACH ROW EXECUTE FUNCTION fn_committee_owner_required();

CREATE TRIGGER trg_committee_owner_before_update
BEFORE UPDATE ON committee
FOR EACH ROW EXECUTE FUNCTION fn_committee_owner_required();

-- =========================================================
-- 12. Stored procedures - PostgreSQL PL/pgSQL equivalents
-- =========================================================

CREATE OR REPLACE PROCEDURE sp_enrol_student(
    p_student_id INTEGER,
    p_offering_id INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_exists INTEGER := 0;
    v_status VARCHAR(20);
    v_capacity INTEGER := 0;
    v_current_enrolments INTEGER := 0;
    v_student_status VARCHAR(20);
BEGIN
    SELECT COUNT(*), MAX(student_status)
    INTO v_exists, v_student_status
    FROM student
    WHERE student_id = p_student_id;

    IF v_exists = 0 THEN
        RAISE EXCEPTION 'Enrolment rejected: student does not exist.';
    END IF;

    IF v_student_status <> 'Active' THEN
        RAISE EXCEPTION 'Enrolment rejected: student is not active.';
    END IF;

    SELECT COUNT(*) INTO v_exists
    FROM course_offering
    WHERE offering_id = p_offering_id;

    IF v_exists = 0 THEN
        RAISE EXCEPTION 'Enrolment rejected: course offering does not exist.';
    END IF;

    SELECT status, capacity
    INTO v_status, v_capacity
    FROM course_offering
    WHERE offering_id = p_offering_id
    FOR UPDATE;

    IF v_status <> 'Offered' THEN
        RAISE EXCEPTION 'Enrolment rejected: course offering is not open.';
    END IF;

    SELECT COUNT(*) INTO v_current_enrolments
    FROM enrolment
    WHERE offering_id = p_offering_id
      AND enrolment_status <> 'Withdrawn';

    IF v_current_enrolments >= v_capacity THEN
        RAISE EXCEPTION 'Enrolment rejected: course offering capacity has been reached.';
    END IF;

    INSERT INTO enrolment (student_id, offering_id, enrolment_date, enrolment_status, result_status)
    VALUES (p_student_id, p_offering_id, CURRENT_DATE, 'Enrolled', 'In progress');

    INSERT INTO dba_audit_log (action_name, action_detail)
    VALUES ('STUDENT_ENROLMENT', CONCAT('student_id=', p_student_id, ', offering_id=', p_offering_id));
END;
$$;

CREATE OR REPLACE PROCEDURE sp_record_student_grade(
    p_lecturer_id INTEGER,
    p_enrolment_id INTEGER,
    p_assessment_type VARCHAR(20),
    p_numeric_grade DECIMAL(5,2)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_locked_enrolment_id INTEGER := NULL;
    v_letter_grade VARCHAR(3);
    v_result_status VARCHAR(20);
BEGIN
    IF p_numeric_grade < 0 OR p_numeric_grade > 100 THEN
        RAISE EXCEPTION 'Grade rejected: numeric grade must be between 0 and 100.';
    END IF;

    v_letter_grade := CASE
        WHEN p_numeric_grade >= 90 THEN 'A'
        WHEN p_numeric_grade >= 80 THEN 'B'
        WHEN p_numeric_grade >= 70 THEN 'C'
        WHEN p_numeric_grade >= 60 THEN 'D'
        ELSE 'F'
    END;

    v_result_status := CASE WHEN p_numeric_grade >= 60 THEN 'Passed' ELSE 'Failed' END;

    SELECT e.enrolment_id INTO v_locked_enrolment_id
    FROM enrolment e
    JOIN course_offering co ON co.offering_id = e.offering_id
    JOIN offering_lecturer ol ON ol.offering_id = co.offering_id
    WHERE e.enrolment_id = p_enrolment_id
      AND ol.lecturer_id = p_lecturer_id
    FOR UPDATE;

    IF v_locked_enrolment_id IS NULL THEN
        RAISE EXCEPTION 'Grade rejected: lecturer is not assigned to this course offering.';
    END IF;

    INSERT INTO grade (
        enrolment_id,
        assessment_type,
        numeric_grade,
        letter_grade,
        recorded_by_lecturer_id
    )
    VALUES (
        p_enrolment_id,
        p_assessment_type,
        p_numeric_grade,
        v_letter_grade,
        p_lecturer_id
    )
    ON CONFLICT (enrolment_id, assessment_type) DO UPDATE SET
        numeric_grade = EXCLUDED.numeric_grade,
        letter_grade = EXCLUDED.letter_grade,
        recorded_by_lecturer_id = EXCLUDED.recorded_by_lecturer_id,
        recorded_at = CURRENT_TIMESTAMP;

    IF p_assessment_type = 'Overall' THEN
        UPDATE enrolment
        SET result_status = v_result_status,
            enrolment_status = 'Completed',
            result_recorded_at = CURRENT_TIMESTAMP
        WHERE enrolment_id = p_enrolment_id;
    END IF;

    INSERT INTO dba_audit_log (action_name, action_detail)
    VALUES ('GRADE_RECORDED', CONCAT('lecturer_id=', p_lecturer_id, ', enrolment_id=', p_enrolment_id));
END;
$$;

-- =========================================================
-- 13. Reporting and privacy views
-- =========================================================

CREATE OR REPLACE VIEW vw_person_masked AS
SELECT
    person_id,
    first_name,
    last_name,
    CONCAT(LEFT(email, 2), '***@', split_part(email, '@', 2)) AS masked_email,
    nationality,
    created_at
FROM person;

CREATE OR REPLACE VIEW vw_student_directory_masked AS
SELECT
    s.student_id,
    s.student_number,
    p.first_name,
    p.last_name,
    CONCAT(LEFT(p.email, 2), '***@', split_part(p.email, '@', 2)) AS masked_email,
    pr.programme_code,
    pr.programme_name,
    s.enrolment_year,
    s.year_of_study,
    s.student_status,
    s.graduation_status
FROM student s
JOIN person p ON p.person_id = s.person_id
JOIN programme pr ON pr.programme_id = s.programme_id;

CREATE OR REPLACE VIEW vw_lecturer_directory_masked AS
SELECT
    l.lecturer_id,
    l.lecturer_number,
    p.first_name,
    p.last_name,
    CONCAT(LEFT(p.email, 2), '***@', split_part(p.email, '@', 2)) AS masked_email,
    d.department_code,
    d.department_name,
    l.academic_rank,
    l.employment_type
FROM lecturer l
JOIN person p ON p.person_id = l.person_id
JOIN department d ON d.department_id = l.department_id;

CREATE OR REPLACE VIEW vw_staff_directory_masked AS
SELECT
    ns.staff_id,
    ns.staff_number,
    p.first_name,
    p.last_name,
    CONCAT(LEFT(p.email, 2), '***@', split_part(p.email, '@', 2)) AS masked_email,
    COALESCE(au.unit_code, d.department_code) AS unit_or_department_code,
    ns.job_title,
    ns.employment_type
FROM non_academic_staff ns
JOIN person p ON p.person_id = ns.person_id
LEFT JOIN administrative_unit au ON au.admin_unit_id = ns.admin_unit_id
LEFT JOIN department d ON d.department_id = ns.department_id;

CREATE OR REPLACE VIEW vw_course_enrolment_summary AS
SELECT
    at.academic_year,
    at.term_name,
    c.course_code,
    c.course_name,
    c.credit_hours,
    co.section_code,
    co.capacity,
    COUNT(e.enrolment_id) AS total_enrolments,
    GREATEST(co.capacity::INTEGER - COUNT(e.enrolment_id)::INTEGER, 0) AS seats_remaining,
    SUM(CASE WHEN e.result_status = 'In progress' THEN 1 ELSE 0 END) AS active_enrolments,
    SUM(CASE WHEN e.result_status = 'Passed' THEN 1 ELSE 0 END) AS passed_count,
    SUM(CASE WHEN e.result_status = 'Failed' THEN 1 ELSE 0 END) AS failed_count
FROM course_offering co
JOIN course c ON c.course_id = co.course_id
JOIN academic_term at ON at.term_id = co.term_id
LEFT JOIN enrolment e ON e.offering_id = co.offering_id
GROUP BY
    at.academic_year,
    at.term_name,
    at.term_sequence,
    c.course_code,
    c.course_name,
    c.credit_hours,
    co.section_code,
    co.capacity;

CREATE OR REPLACE VIEW vw_student_result_summary AS
SELECT
    s.student_id,
    s.student_number,
    CONCAT(p.first_name, ' ', p.last_name) AS student_name,
    pr.programme_code,
    s.year_of_study,
    COUNT(DISTINCT e.enrolment_id) AS total_course_records,
    AVG(CASE WHEN g.assessment_type = 'Overall' THEN g.numeric_grade END) AS average_overall_grade,
    SUM(CASE WHEN e.result_status = 'Passed' THEN 1 ELSE 0 END) AS passed_courses,
    SUM(CASE WHEN e.result_status = 'Failed' THEN 1 ELSE 0 END) AS failed_courses,
    SUM(CASE WHEN e.result_status = 'In progress' THEN 1 ELSE 0 END) AS active_courses
FROM student s
JOIN person p ON p.person_id = s.person_id
JOIN programme pr ON pr.programme_id = s.programme_id
LEFT JOIN enrolment e ON e.student_id = s.student_id
LEFT JOIN grade g ON g.enrolment_id = e.enrolment_id
GROUP BY
    s.student_id,
    s.student_number,
    p.first_name,
    p.last_name,
    pr.programme_code,
    s.year_of_study;

CREATE OR REPLACE VIEW vw_lecturer_workload AS
SELECT
    at.academic_year,
    at.term_name,
    l.lecturer_id,
    l.lecturer_number,
    CONCAT(p.first_name, ' ', p.last_name) AS lecturer_name,
    d.department_code,
    COUNT(DISTINCT ol.offering_id) AS number_of_course_offerings,
    SUM(ol.workload_credit_hours) AS total_workload_credit_hours,
    COUNT(e.enrolment_id) AS total_students
FROM offering_lecturer ol
JOIN lecturer l ON l.lecturer_id = ol.lecturer_id
JOIN person p ON p.person_id = l.person_id
JOIN department d ON d.department_id = l.department_id
JOIN course_offering co ON co.offering_id = ol.offering_id
JOIN academic_term at ON at.term_id = co.term_id
LEFT JOIN enrolment e ON e.offering_id = co.offering_id
GROUP BY
    at.academic_year,
    at.term_name,
    at.term_sequence,
    l.lecturer_id,
    l.lecturer_number,
    p.first_name,
    p.last_name,
    d.department_code;

CREATE OR REPLACE VIEW vw_programme_credit_summary AS
SELECT
    pr.programme_code,
    pr.programme_name,
    pr.degree_awarded,
    pr.required_credit_hours,
    COALESCE(SUM(CASE WHEN pcr.is_required_for_graduation THEN c.credit_hours ELSE 0 END), 0) AS required_course_credit_hours,
    COALESCE((
        SELECT SUM(eg.minimum_credit_hours)
        FROM elective_group eg
        WHERE eg.programme_id = pr.programme_id
    ), 0) AS required_elective_credit_hours
FROM programme pr
LEFT JOIN programme_course_requirement pcr ON pcr.programme_id = pr.programme_id
LEFT JOIN course c ON c.course_id = pcr.course_id
GROUP BY
    pr.programme_id,
    pr.programme_code,
    pr.programme_name,
    pr.degree_awarded,
    pr.required_credit_hours;

CREATE OR REPLACE VIEW vw_prerequisite_progress AS
SELECT
    s.student_number,
    CONCAT(p.first_name, ' ', p.last_name) AS student_name,
    c.course_code AS target_course,
    pc.course_code AS prerequisite_course,
    cp.prerequisite_type,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM enrolment e
            JOIN course_offering co ON co.offering_id = e.offering_id
            WHERE e.student_id = s.student_id
              AND co.course_id = cp.prerequisite_course_id
              AND e.result_status = 'Passed'
        ) THEN 'Completed'
        ELSE 'Not completed'
    END AS prerequisite_status
FROM student s
JOIN person p ON p.person_id = s.person_id
CROSS JOIN course_prerequisite cp
JOIN course c ON c.course_id = cp.course_id
JOIN course pc ON pc.course_id = cp.prerequisite_course_id;

CREATE OR REPLACE VIEW vw_research_project_summary AS
SELECT
    rp.project_code,
    rp.project_title,
    rg.group_name,
    CONCAT(pi_person.first_name, ' ', pi_person.last_name) AS principal_investigator,
    rp.project_status,
    COUNT(DISTINCT rpm.project_member_id) AS team_member_count,
    COUNT(DISTINCT pf.project_funding_id) AS funding_source_count,
    COUNT(DISTINCT pp.publication_id) AS publication_count,
    COUNT(DISTINCT po.outcome_id) AS outcome_count
FROM research_project rp
JOIN research_group rg ON rg.research_group_id = rp.research_group_id
JOIN lecturer pi_lecturer ON pi_lecturer.lecturer_id = rp.principal_investigator_id
JOIN person pi_person ON pi_person.person_id = pi_lecturer.person_id
LEFT JOIN research_project_member rpm ON rpm.project_id = rp.project_id
LEFT JOIN project_funding pf ON pf.project_id = rp.project_id
LEFT JOIN project_publication pp ON pp.project_id = rp.project_id
LEFT JOIN project_outcome po ON po.project_id = rp.project_id
GROUP BY
    rp.project_id,
    rp.project_code,
    rp.project_title,
    rg.group_name,
    pi_person.first_name,
    pi_person.last_name,
    rp.project_status;

CREATE OR REPLACE VIEW vw_publications_past_year AS
SELECT
    pub.publication_code,
    pub.title,
    pub.publication_type,
    pub.publication_year,
    l.lecturer_number,
    CONCAT(p.first_name, ' ', p.last_name) AS lecturer_name
FROM publication pub
JOIN lecturer_publication lp ON lp.publication_id = pub.publication_id
JOIN lecturer l ON l.lecturer_id = lp.lecturer_id
JOIN person p ON p.person_id = l.person_id
WHERE pub.publication_year >= CAST(EXTRACT(YEAR FROM CURRENT_DATE) AS SMALLINT) - 1;



-- =========================================================
-- 14. Roles for demonstration
-- =========================================================

DROP ROLE IF EXISTS use_reporter_role;
DROP ROLE IF EXISTS use_admin_role;
DROP ROLE IF EXISTS use_lecturer_role;
DROP ROLE IF EXISTS use_student_role;

CREATE ROLE use_reporter_role;
CREATE ROLE use_admin_role;
CREATE ROLE use_lecturer_role;
CREATE ROLE use_student_role;

GRANT USAGE ON SCHEMA use_record_management TO use_reporter_role, use_admin_role, use_lecturer_role, use_student_role;

GRANT SELECT ON use_record_management.vw_person_masked TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_student_directory_masked TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_lecturer_directory_masked TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_staff_directory_masked TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_course_enrolment_summary TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_programme_credit_summary TO use_reporter_role;
GRANT SELECT ON use_record_management.vw_research_project_summary TO use_reporter_role;

GRANT SELECT, INSERT, UPDATE ON use_record_management.course TO use_admin_role;
GRANT SELECT, INSERT, UPDATE ON use_record_management.course_offering TO use_admin_role;
GRANT SELECT, INSERT, UPDATE ON use_record_management.programme TO use_admin_role;
GRANT SELECT, INSERT, UPDATE ON use_record_management.academic_term TO use_admin_role;

GRANT SELECT ON use_record_management.course TO use_lecturer_role;
GRANT SELECT ON use_record_management.course_offering TO use_lecturer_role;
GRANT SELECT ON use_record_management.offering_lecturer TO use_lecturer_role;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA use_record_management TO use_lecturer_role;

GRANT SELECT ON use_record_management.course TO use_student_role;
GRANT SELECT ON use_record_management.course_offering TO use_student_role;
GRANT SELECT ON use_record_management.academic_term TO use_student_role;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA use_record_management TO use_student_role;

SELECT 'USE PostgreSQL schema, triggers, procedures, views and roles created' AS message;
